/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Gradebook.Assignment;
import Gradebook.Category;
import Gradebook.Course;
import Gradebook.Gradebook;
import Gradebook.IGradeable;
import org.junit.experimental.categories.Categories;

/**
 *
 * @author Tom
 */
public class GradeDistributionSelection extends javax.swing.JDialog {
    private Gradebook m_gradebook;
    private IGradeable m_gradeable;
    private Course m_course;
    /**
     * Creates new form GradeDistributionSelection
     */
    public GradeDistributionSelection(java.awt.Frame parent, boolean modal, Gradebook gradebook) {
        super(parent, modal);
        initComponents();
        this.setTitle("Grade Distribution");
        buttonGroup1.add(courseButton);
        buttonGroup1.add(assignmentButton);
        coursePanel.setVisible(false);
        assignmentPanel.setVisible(false);
        m_gradebook = gradebook;
    }
    
    public IGradeable getGradable(){
        return m_gradeable;
    }
    public Course getCourse(){
        return m_course;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        courseButton = new javax.swing.JRadioButton();
        assignmentButton = new javax.swing.JRadioButton();
        coursePanel = new javax.swing.JPanel();
        courseComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        assignmentPanel = new javax.swing.JPanel();
        assignmentComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        okButton = new GUI.ImageButton();
        cancelButton = new GUI.ImageButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseButton.setText("Course");
        courseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(courseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, -1));

        assignmentButton.setText("Assignment");
        assignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(assignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 9, -1, -1));

        coursePanel.setEnabled(false);
        coursePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });
        coursePanel.add(courseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 158, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Select a Course");
        coursePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel1.add(coursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 182, 87));

        assignmentPanel.setEnabled(false);
        assignmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentComboBoxActionPerformed(evt);
            }
        });
        assignmentPanel.add(assignmentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 172, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Select an Assignment");
        assignmentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel1.add(assignmentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 194, 87));

        okButton.setText("Ok");
        okButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 53, 24));

        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 68, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButtonActionPerformed
        if(courseButton.isSelected()){
            assignmentPanel.setVisible(false);
            assignmentButton.setSelected(false);
            coursePanel.setVisible(true);
            courseComboBox.removeAllItems();
            assignmentComboBox.removeAllItems();
            for(Course course : m_gradebook.getCourses()){
                courseComboBox.addItem(course);
            }
        }
    }//GEN-LAST:event_courseButtonActionPerformed

    private void assignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentButtonActionPerformed
        if(assignmentButton.isSelected()){
            courseButton.setSelected(false);
            coursePanel.setVisible(true);
            courseComboBox.removeAllItems();
            assignmentComboBox.removeAllItems();
            for(Course course : m_gradebook.getCourses()){
                courseComboBox.addItem(course);
            }
        }
    }//GEN-LAST:event_assignmentButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        if(courseButton.isSelected()){
            if(courseComboBox.getSelectedIndex() != -1){
                Course course = (Course)courseComboBox.getSelectedItem();
                m_gradeable = course;
                m_course = course;
            }
        }else{
            if(courseComboBox.getSelectedIndex() != -1){
                Course course = (Course)courseComboBox.getSelectedItem();
                assignmentComboBox.removeAllItems();
                for(Category category : course.getCategories()){
                    for(Assignment assignment : category.getAssignments()){
                        assignmentComboBox.addItem(assignment);
                    }
                }
                assignmentPanel.setVisible(true);
            }
        }
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void assignmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentComboBoxActionPerformed
        if(assignmentComboBox.getSelectedIndex() != -1){
            Assignment assignment = (Assignment)assignmentComboBox.getSelectedItem();
            m_gradeable = assignment;
            m_course = (Course)courseComboBox.getSelectedItem();
        }
    }//GEN-LAST:event_assignmentComboBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        m_gradeable = null;
        m_course = null;
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton assignmentButton;
    private javax.swing.JComboBox assignmentComboBox;
    private javax.swing.JPanel assignmentPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private GUI.ImageButton cancelButton;
    private javax.swing.JRadioButton courseButton;
    private javax.swing.JComboBox courseComboBox;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private GUI.ImageButton okButton;
    // End of variables declaration//GEN-END:variables
}
