/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import javax.imageio.ImageIO;

/**
 *
 * @author Eric
 */
public class NewExistingCourse extends javax.swing.JDialog {

    /**
     * Creates new form NewExistingCourse
     * @param parent
     * @param modal
     */
    public NewExistingCourse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public enum Action { None, New, Copy };
    private Action m_action = Action.None;
    public Action getAction() {
        return m_action;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageButton2 = new GUI.ImageButton();
        imageButton1 = new GUI.ImageButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Course");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Add a Course");

        imageButton2.setText("Copy");
        imageButton2.setToolTipText("");
        imageButton2.setFocusable(false);
        imageButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        imageButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButton2ActionPerformed(evt);
            }
        });

        imageButton1.setText("New");
        imageButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        imageButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("<html>\n\nWould you like to create a new course, or copy an existing course?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        try {
            imageButton2.setImage(ImageIO.read(this.getClass().getResource("resources/Copy.png")));
        }
        catch (Exception e) {}
        try {
            imageButton1.setImage(ImageIO.read(this.getClass().getResource("resources/CreateNew.png")));
        }
        catch (Exception e) {}

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButton2ActionPerformed
        m_action = Action.Copy;
        setVisible(false);
    }//GEN-LAST:event_imageButton2ActionPerformed

    private void imageButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButton1ActionPerformed
        m_action = Action.New;
        setVisible(false);
    }//GEN-LAST:event_imageButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ImageButton imageButton1;
    private GUI.ImageButton imageButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
